package com.wigwag.wwutils.Interface;

public interface HttpStatus {
    int WW_ACCEPTED = 202;
    int WW_BAD_GATEWAY = 502;
    int WW_BAD_REQUEST = 400;
    int WW_CONFLICT = 409;
    int WW_CONTINUE = 100;
    int WW_CREATED = 201;
    int WW_EXPECTATION_FAILED = 417;
    int WW_FAILED_DEPENDENCY = 424;
    int WW_FORBIDDEN = 403;
    int WW_GATEWAY_TIMEOUT = 504;
    int WW_GONE = 410;
    int WW_HTTP_VERSION_NOT_SUPPORTED = 505;
    int WW_INSUFFICIENT_SPACE_ON_RESOURCE = 419;
    int WW_INSUFFICIENT_STORAGE = 507;
    int WW_INTERNAL_SERVER_ERROR = 500;
    int WW_LENGTH_REQUIRED = 411;
    int WW_LOCKED = 423;
    int WW_METHOD_FAILURE = 420;
    int WW_METHOD_NOT_ALLOWED = 405;
    int WW_MOVED_PERMANENTLY = 301;
    int WW_MOVED_TEMPORARILY = 302;
    int WW_MULTIPLE_CHOICES = 300;
    int WW_MULTI_STATUS = 207;
    int WW_NON_AUTHORITATIVE_INFORMATION = 203;
    int WW_NOT_ACCEPTABLE = 406;
    int WW_NOT_FOUND = 404;
    int WW_NOT_IMPLEMENTED = 501;
    int WW_NOT_MODIFIED = 304;
    int WW_NO_CONTENT = 204;
    int WW_OK = 200;
    int WW_PARTIAL_CONTENT = 206;
    int WW_PAYMENT_REQUIRED = 402;
    int WW_PRECONDITION_FAILED = 412;
    int WW_PROCESSING = 102;
    int WW_PROXY_AUTHENTICATION_REQUIRED = 407;
    int WW_REQUESTED_RANGE_NOT_SATISFIABLE = 416;
    int WW_REQUEST_TIMEOUT = 408;
    int WW_REQUEST_TOO_LONG = 413;
    int WW_REQUEST_URI_TOO_LONG = 414;
    int WW_RESET_CONTENT = 205;
    int WW_SEE_OTHER = 303;
    int WW_SERVICE_UNAVAILABLE = 503;
    int WW_SWITCHING_PROTOCOLS = 101;
    int WW_TEMPORARY_REDIRECT = 307;
    int WW_UNAUTHORIZED = 401;
    int WW_UNPROCESSABLE_ENTITY = 422;
    int WW_UNSUPPORTED_MEDIA_TYPE = 415;
    int WW_USE_PROXY = 305;



    int WW_NO_CLOUD = 901;
}